# Generated by Django 4.2.7 on 2025-10-25 11:59
"""Начальная схема ml_service: MLModel и PredictionLog."""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Создаёт таблицы учёта моделей и истории предсказаний."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('model_type', models.CharField(choices=[('content_moderation', 'Модерация контента'), ('spam_detection', 'Обнаружение спама'), ('sentiment_analysis', 'Анализ тональности')], max_length=50, verbose_name='Тип модели')),
                ('model_path', models.CharField(max_length=200, verbose_name='Путь к модели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Точность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Модель',
                'verbose_name_plural': 'ML Модели',
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='Тип контента')),
                ('content_id', models.PositiveIntegerField(verbose_name='ID контента')),
                ('text', models.TextField(verbose_name='Текст')),
                ('prediction', models.CharField(max_length=50, verbose_name='Предсказание')),
                ('confidence', models.FloatField(verbose_name='Уверенность')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Корректно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_service.mlmodel')),
            ],
            options={
                'verbose_name': 'Лог предсказания',
                'verbose_name_plural': 'Логи предсказаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
