# Generated by Django 4.2.7 on 2025-10-25 11:59
"""Начальная миграция: создание модели глобальных настроек сайта SiteSettings."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Применяет начальную схему таблицы настроек (одна логическая запись на приложение)."""

    initial = True

    dependencies = [
    ]

    operations = [
        # Таблица SiteSettings: название, контакты, флаги модерации и лимит изображений
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Доска объявлений', max_length=100, verbose_name='Название сайта')),
                ('site_description', models.TextField(blank=True, verbose_name='Описание сайта')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('moderation_enabled', models.BooleanField(default=True, verbose_name='Включена модерация')),
                ('ml_moderation_enabled', models.BooleanField(default=True, verbose_name='Включена ML-модерация')),
                ('max_images_per_ad', models.PositiveIntegerField(default=10, verbose_name='Максимум изображений на объявление')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
